### ISSUE TITLE
SITE

### ISSUE THREAD

**Issue by willweinstein** [willweinstein/HEXRTYPE#1]
@thatoddmailbox @medensqui @em-p @c20et @nywillb YOU MAY ALL WONDER WHY YOU HAVE BEEN CONJURED HERE. WE ARE ABOUT TO EMBARK ON A GREAT JOURNEY. ONE THAT CARRIES US FAR PAST SPUT_OOT AND INTO DEEP DARK REALM OF HEXRS. WE MUST DEFEAT THE EVIL LOGIC CHIP AND TAKE BACK OUR INTERWEBS!!! NOW, THIS GITHUB WILL BE THE CREATION OF SOMETHING NEW AND INSPIRATIONAL. HERE'S WHAT IT IS:
I AM SURE YOU ARE ALL AWARE OF HACKERTYPER.NET
WE WILL FORM HEXRTYPE.TK
IT WILL BE BASICALLY THE SAME EXCEPT FOR THE FOLLOWING:
1. IT WILL TYPE IN HEX
2. IT WILL HAVE A TONNE OF EASTER EGGS
3. MORE EASTER EGGS
4. KONAMI CODE STUFFS (EASTER EGGS)

**Comment by thatoddmailbox** [comment]
@willweinstein 

> TONNE

ARE YOU BRITISH?

Translation for confused people:
hackertyper.net, but in Hex. and lots of easter eggs.

**Comment by willweinstein** [comment]
@thatoddmailbox NU EYEM JOOST AE GRIT HXR

**Comment by willweinstein** [comment]
@thatoddmailbox PUBLIC RELEASE IS IN 1 HOUR LETS GET WORKING!

**Comment by medensqui** [comment]
@thatoddmailbox Ah. And actually wtf is this

**Comment by thatoddmailbox** [comment]
@medensqui It is the @willweinstein version of hackertyper.net (hexrtype) with more easter eggs.

**Comment by medensqui** [comment]
@thatoddmailbox Ah.

I EDITED THE READ ME YAY

**Comment by thatoddmailbox** [comment]
@medensqui YAY I DID IT! GO TO [THIS SITE](http://willweinstein.github.io/HEXRTYPE)!
